In [2]:
import numpy as np

In [3]:
# Create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype)

arr2 = np.array([1, 2, 3, 4, 5, "Adnan"])
print(arr2, type(arr2), arr2.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'Adnan'] <class 'numpy.ndarray'> <U21


# Shape

In [4]:
# Create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "Adnan"])
print(arr2, type(arr2), arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'Adnan'] <class 'numpy.ndarray'> (6,)


# 2D Array

In [7]:
arr2d = np.array([[1,2,3,], [4,5,6],[7,8,9]])
print(arr2d, arr2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
