In [1]:
import numpy as np

In [2]:
# Create 
arr1 = np.zeros((2, 3), dtype = "int64") # prefill
print(arr1, arr1.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [3]:
arr2 = np.ones((2, 3)) # Prefill
print(arr2, arr2.shape)

[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)


In [5]:
arr3 = np.full((3, 4), 100) # Prefill with val
print(arr3, arr3.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


In [6]:
arr4 = np.eye(7) # identiy matrix
print(arr4, arr4.shape)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]] (7, 7)


In [8]:
arr5 = np.arange(0, 11, 2) # range elements
print(arr5, arr5.shape)

[ 0  2  4  6  8 10] (6,)


In [9]:
arr6 = np.linspace(1, 100, 4) # evenly spaced array
print(arr6, arr6.shape)

[  1.  34.  67. 100.] (4,)


In [14]:
# Properties
arr = np.array([[1,2,3], [4,5,6],[7,8,9]])

print(arr.shape) # Dimensions = m x n
print(arr.size) # tot els - 9
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


# Reshape 

In [19]:
# Operations of array

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr, arr.shape)

reshaped = arr.reshape((3,3))
print(reshaped, reshaped.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [21]:
# Flattend 
# Operations of array

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr, arr.shape)

# reshaped = arr.reshape((3,3))
# print(reshaped, reshaped.shape)

flattened = arr.flatten() # 2D => 1D
print(flattened)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
[1 2 3 4 5 6 7 8 9]


# Indexing

In [23]:
# arr = np.array([1, 2, 3, 4, 5])
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0][2])

3


# Fancy Indexing

In [24]:
arr = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


# Boolean Indexing

In [28]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]


# Slicing Operations

In [33]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4]) # [Start, end, step]
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


# Copy vs view

In [37]:
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

arr = np.array([1, 2, 3, 4, 5])

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [40]:
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[  1 200   3   4   5]


# Dot copy

In [41]:
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


# Data Type

In [42]:
arr = np.array([1, 2, 3.14, 4, 5, "Anum"])

print(arr, arr.dtype)

['1' '2' '3.14' '4' '5' 'Anum'] <U32


# Complex number

In [47]:
arr1 = np.array([3 + 5j])
arr2 = np.array([2 + 3j])

print(arr1, arr1.dtype)
print(arr1 + arr2)
print(arr1 - arr2)

[3.+5.j] complex128
[5.+8.j]
[1.+2.j]


# String

In [ ]:
arr = np.array(["prime", {1, 2, 3}, 3.14])
print(arr, arr)