In [2]:
import numpy as np

# Multi-dimensional arrays

In [3]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]


# Rows

In [5]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[ 6 15 24]


# slicing

In [6]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[ 6 15 24]
[[2]
 [5]]


# 3D Array

In [7]:
# 3D array

arr3D = np.array([[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]])

print(arr3D, arr3D.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]] (1, 6, 2)


# Indexing

In [10]:
# 3D array
arr3D = np.array([[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]])

print(arr3D, arr3D.shape)

print(arr3D[0, 1, 0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]] (1, 6, 2)
3


# Slicing

In [12]:
# 3D array
arr3D = np.array([[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]])

print(arr3D, arr3D.shape)

print(arr3D[0, 1, 0])

print(arr3D[:, 0, :]) # First row from both layers
print(arr3D[:, :, 0])


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]] (1, 6, 2)
3
[[1 2]]
[[ 1  3  5  7  9 11]]


# Vectorization & Broadcasting

In [17]:
# Vectorization 

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(arr1 ** 2)
print(arr1 + 12)
print(arr1 + arr2)

[ 1  4  9 16 25]
[13 14 15 16 17]
[ 7  9 11 13 15]


# Broadcasting

In [21]:
arr = np.array([1, 2, 3, 4, 5])

print(arr + 7)


arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[6, 7, 8, 9, 10],[1, 2, 3, 4, 5]])

print(arr1 + arr2)
print(arr1.shape)
print(arr2.shape)

[ 8  9 10 11 12]
[[ 7  9 11 13 15]
 [ 2  4  6  8 10]]
(5,)
(2, 5)


# Normalization

In [27]:
arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean) / std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


# importance Mathematical Functions

In [33]:
# Aggregations

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


# Power FNX

In [35]:
arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


# Log

In [36]:
arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]


# Exponenant

In [37]:
arr = np.array([1, 2, 3, 4, 5])

print(np.exp(arr))


[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


# Rounding

In [44]:
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1, 2, 3, 2, 6, 3, 4, 5])

print(np.unique(arr))

3.0
4.0
3.0
3.0
[1 2 3 4 5 6]


# Absolute

In [45]:
arr = np.array([1, 2, 3, -2, 6, 3, -4, 5])

print(np.abs(arr))

[1 2 3 2 6 3 4 5]
